### ISSUE TITLE
Ensure Tomcat Starts with Security Manager

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds-docker#102]
The [parent container](https://github.com/Unidata/tomcat-docker) has hooks (`start-tomcat.sh`)for starting Tomcat with security manager.

**Comment by julienchastang** [comment]
Won't do for now since this change will probably require significant changes to the `catalina.policy` file.

**Comment by gajowi** [comment]
I think the current setup (with the security manager) is broken.  I get:
17-Nov-2016 08:51:54.217 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory The web application with context path [/thredds] was not deployed because it contained a deployment descriptor [/usr/local/tomcat/webapps/thredds/META-INF/context.xml] which may include configuration necessary for the secure deployment of the application but processing of deployment descriptors is prevented by the deployXML setting of this host. An appropriate descriptor should be created at [/usr/local/tomcat/conf/Catalina/localhost/thredds.xml] to deploy this application.

Do you need to back out some changes to avoid using start-tomcat.sh for now?

**Comment by julienchastang** [comment]
Hi Gareth,

The THREDDS `entrypoint.sh` ([inherited from the parent container](https://github.com/Unidata/tomcat-docker/blob/master/entrypoint.sh)) starts the container with `CMD ["catalina.sh", "run"]` and not `start-tomcat.sh` (see [here](https://github.com/Unidata/thredds-docker/blob/master/Dockerfile#L141)) therefore the security manager is not invoked in the present setup.

Please make extra sure that you have the "latest" version of whatever container version you are using with a `docker pull` (e.g., `docker pull unidata/thredds-docker:4.6.6`).

**Comment by gajowi** [comment]
Ah my mistake...

I've been building the thredds-docker container but pulling the parent container while I sort out  my idea of a clean approach to an operational service.

The test I ran was pulling from my own fork of the project where I was testing if a trivial change would enable the security manager.

Sorry for the noise. I'll try to be more careful keeping track of my own setup!

**Comment by julienchastang** [comment]
Great, thanks for the good news.
