### ISSUE TITLE
what is 4.6.12-snapshot?

### ISSUE THREAD

**Issue by SvenDowideit** [Unidata/thredds-docker#203]
is it the 4.6.12 release? or is it a release candidate?

should there be a tag for it in this git repo too?

**Comment by julienchastang** [comment]
`4.6.12-SNAPSHOT` branch of this project aligns to the `4.6.12-SNAPSHOT` release of the THREDDS project. So no it is not a release, it is an evolving SNAPSHOT.

The `Dockerfile` [describes it best](https://github.com/Unidata/thredds-docker/blob/4.6.12-SNAPSHOT/Dockerfile#L81).

I don't favor a tag since the SNAPSHOT can evolve for both projects.

**Comment by SvenDowideit** [comment]
cool - so basically, its a pre-beta development image built on a branch - cool
