### ISSUE TITLE
 THREDDS 5.0 beta2

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds-docker#204]
per @rsignell-usgs 

https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/tds/5.0.0-beta1/tds-5.0.0-beta1.war

**Comment by lesserwhirls** [comment]
Let's aim for beta2: https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/tds/5.0.0-beta2/tds-5.0.0-beta2.war

**Comment by julienchastang** [comment]
Alrighty. I'll get to this as soon as I can.

**Comment by rsignell-usgs** [comment]
@julienchastang and I tried to build the beta2 docker container this week and failed due to intermittent curl problems.   He then gave me the Dockerfile and it took 5 tries before I didn't get the curl error, and built the container.    So nothing wrong with the Dockerfile, but something wrong with the network?

**Comment by julienchastang** [comment]
We should parameterize `curl` with retry options.

**Comment by rsignell-usgs** [comment]
Maybe like this:
https://stackoverflow.com/a/13554435

**Comment by julienchastang** [comment]
@m1schmidt narrowed in on the issue at hand: https://github.com/kontena/kontena/issues/3327

**Comment by julienchastang** [comment]
Done:
- https://hub.docker.com/r/unidata/thredds-docker/builds/
- https://github.com/Unidata/thredds-docker/tree/5.0-beta2
