### ISSUE TITLE
Set hostname

### ISSUE THREAD

**Issue by schafer14** [Unidata/thredds-docker#222]
I'm trying to set the base url that thredds uses in a docker container using the TDS_HOST environment variable, but I'm am still getting urls with the localhost domain. The command I am running is

```
docker run \
	--rm \
	-e TDS_HOST=my-domain.com \
	--name some-thredds \
	-d \
	-p 5454:8080  \
	-v $(pwd)/conf/:/usr/local/tomcat/content/thredds/ \
	-v $(pwd)/ncss:/data/thredds/scratch \
	-v $(pwd)/server.xml:/usr/local/tomcat/conf/server.xml \
	unidata/thredds-docker
```

Am I understanding that environment variable correctly? How can I get relative links to use a specific domain?

**Comment by schafer14** [comment]
Yeah I'm not using TDM. I'm new to Thredds so I am not certain what it is and that caused me to get a little confused with the documentation.

When I run the command you sent everything works but still uses localhost as the base url. You are correct I am trying to access from http://thredds.domain.com/thredds/catalog.html I am using a reverse proxy (nginx) to handle routing. 

I did have that thought that it could be thredds configuration and people have mentioned it could be tomcat config as well. I mounted configuration files for thredds (`threddsConfig.xml` and `catalog.xml` and the tomcat `server.xml`) in docker but that didn't seem to help. Reading the thredds docs I haven't been able to figure out the correct configurations yet.

**Comment by julienchastang** [comment]
So if http://localhost:8080/thredds/catalog.html works the next step is to get http://thredds.domain.com:8080/thredds/catalog.html working. At this point, this problem lies outside this THREDDS docker container. Do you have DNS control over the IP address where this THREDDS server is running? I'd say the next logical step is to get this working *without* a reverse proxy just to ensure we can make it that far. Then as a last step incorporate the reverse proxy. 

I've done this reverse proxy type setup before. I recall it not being totally easy to get right. You can find what I did at this [now defunct project](https://github.com/Unidata/Unidata-Dockerfiles/blob/master/jetstream/docker-compose.yml).  It uses a technology called traefik in conjunction with nginx. The idea there is I was running a RAMADDA server and a TDS on the same host and I needed a way to distinguish the two with a URL path (e.g., mydomain.com/thredds vs. mydomain.com/ramadda).

**Comment by schafer14** [comment]
Alright, thanks for that.

**Comment by Alexander-Barth** [comment]
For the record, I had a similar issue than described initially. I am running the docker container behind an apache reverse proxy. 
The data files are accessible under e.g. http://opendap2.oceanbrowser.net/thredds/dodsC/data/mydata.nc.html but the resulting html contain internal reference starting with http://localhost... .
The solution for me was to activate ProxyPreserveHost in the apache configuration file (https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost). For example:

```
<Location "/">
            ProxyPass http://localhost:8081/
            ProxyPassReverse http://localhost:8081/
            ProxyPreserveHost On
</Location>
```
