### ISSUE TITLE
5.3 tagging anomaly

### ISSUE THREAD

**Issue by gajowi** [Unidata/thredds-docker#258]
I see the readme currently suggests there is a 5.3 tag but I only see a 5.3-SNAPSHOT tag.
Is there an issue with the update procedure?
I'm keen to have 5.4 in a container as soon as possible after it becomes available upstream.

**Comment by gajowi** [comment]
BTW I am aware of: https://github.com/Unidata/thredds-docker/issues/242  It would be nice to have a clear description of the release process and versioning, perhaps under: https://github.com/Unidata/thredds-docker#h8766A6B1

**Comment by julienchastang** [comment]
Hi Gareth. Sorry about that. `5.3` should have been release along with `4.6.19`, but because of an error on my part (I forgot to actually push out the branch after creating it) that did not happen. You can now find `5.3` as expected.

>nice to have a clear description of the release process and versioning

Shortly after a TDS version is released a Docker version for that corresponding version is also released. That does not mean though that that container will remain static as we also update the container based on upstream tomcat changes. This is the modus operandi of for other canonical containers (e.g., the official tomcat image).

**Comment by julienchastang** [comment]
BTW: I just released `4.6.20` and `5.4` SNAPSHOTS. See here: https://hub.docker.com/r/unidata/thredds-docker/tags?page=1&ordering=last_updated
