### ISSUE TITLE
Thredds server inserts html comment before DAP2 response, causing failures

### ISSUE THREAD

**Issue by mikegratton** [Unidata/thredds-docker#293]
Version: 5.4

Environment: Docker container run on RHEL7/8 workstations

Description:
Depending on the URL, the thredds server will respond to GET requests with an inserted HTML comment:
```
<!-- IE friendly error message walkround.
     if error message from server is less than
     512 bytes IE v5+ will use its own error
     message instead of the one returned by
     server.                                 -->
```
This comment breaks libnetcdf DAP2, which doesn't expect an http comment. Unfortunately, I'm not sure what triggers this.  Is there a way to disable the comment in tomcat?

Using curl, here is the header of the request that triggers a comment being sent:
```
HTTP/1.1 504 Gateway Timeout
Content-Type: text/html
Cache-Control: no-cache
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: frame-ancestors 'self'
Content-Length: 5112
```
versus for the one where the comment is NOT sent:
```
HTTP/1.1 200
Strict-Transport-Security: max-age=0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
vary: Origin
Content-Type: text/html;charset=UTF-8
Content-Language: en-US
Transfer-Encoding: chunked
Date: Thu, 06 Jul 2023 15:03:25 GMT
Server: Apache
```

**Comment by ana-v-espinoza** [comment]
Hello,

I spoke with some of our THREDDS engineers (this repository is for maintaining the containerized version of THREDDS), and, without more information to go on, they suspect this issue is not related to THREDDS or Tomcat.

Specifically, we think that ultimately the underlying issue is this 504 error that is likely generated by a proxy server that timed out when the DAP service didn't reponse quickly enough for how it's configured.

I'm closing this issue here, as it seems like your issue isn't related to Docker, however, if you still need further support, please contact the THREDDS team at `support-thredds(at)unidata.ucar.edu`.

Thank you,
--
Ana
